# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.

include: package:lint/analysis_options.yaml

analyzer:
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: true

linter:
  rules:
    constant_identifier_names: false
    depend_on_referenced_packages: false
    avoid_dynamic_calls: false
    sort_pub_dependencies: false
